apiVersion: v1
kind: Service
metadata:
  name: green-ai-service
  namespace: default
spec:
  selector:
    app: green-ai
  ports:
    - name: http
      port: 8000        # Service port
      targetPort: 8000  # Container port
  type: ClusterIP
